### ISSUE TITLE
Offline permission error

### ISSUE THREAD

**Issue by Wiener234** [brahmkshatriya/echo#17]
It is not possible to play any song except the ones that came with the phone. 

Storage permission is set. 

Android: 10 (Huawai) 
Version: newest and alot of old ones

Crash log:

```
Client : echo_offline
Track : Track(id=595741, title=Alone, artists=[Artist(id=-237349610, name=Avril Lavigne, cover=null, extras={}, subtitle=null, description=null, followers=null, isFollowing=false)], album=Album(id=54, title=The Best Damn Thing (Expanded Edition), cover=null, artists=[], tracks=null, releaseDate=null, publisher=null, duration=null, description=null, subtitle=null, extras={}), cover=UriImageHolder(uri=content://media/external/audio/media/595741/albumart, crop=false), duration=193752, plays=null, releaseDate=null, liked=false, extras={}, videoStreamable=[], audioStreamables=[Streamable(id=file:///storage/emulated/0/Music/Avril%20Lavigne/The%20Best%20Damn%20Thing%20(Expanded%20Edition)%20(Disc%201)/13%20-%20Avril%20Lavigne%20-%20The%20Best%20Damn%20Thing%20(Expanded%20Edition)%20(Disc%201)%20-%20Alone.mp3, quality=0, extra={})], expiresAt=0)
Stream : Streamable(id=file:///storage/emulated/0/Music/Avril%20Lavigne/The%20Best%20Damn%20Thing%20(Expanded%20Edition)%20(Disc%201)/13%20-%20Avril%20Lavigne%20-%20The%20Best%20Damn%20Thing%20(Expanded%20Edition)%20(Disc%201)%20-%20Alone.mp3, quality=0, extra={})

androidx.media3.datasource.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /storage/emulated/0/Music/Avril Lavigne/The Best Damn Thing (Expanded Edition) (Disc 1)/13 - Avril Lavigne - The Best Damn Thing (Expanded Edition) (Disc 1) - Alone.mp3: open failed: EACCES (Permission denied)
	at androidx.media3.datasource.FileDataSource.openLocalFile(FileDataSource.java:205)
	at androidx.media3.datasource.FileDataSource.open(FileDataSource.java:116)
	at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
	at dev.brahmkshatriya.echo.playback.StreamableDataSource.open(StreamableDataSource.kt:58)
```

**Comment by oge2k** [comment]
Here to add that a device umidigi a9 pro with android 10 also has the same issues
