### ISSUE TITLE
[Bug] Bluetooth crashed when playing audio

### ISSUE THREAD

**Issue by dxuser1919** [brahmkshatriya/echo#18]
FATAL EXCEPTION: main
Process: com.android.bluetooth, PID: 13395
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: dev.brahmkshatriya.echo.common.models.Track
	at android.os.Parcel.readParcelableCreator(Parcel.java:3367)
	at android.os.Parcel.readParcelable(Parcel.java:3272)
	at android.os.Parcel.readValue(Parcel.java:3174)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3570)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
	at android.os.Bundle.putAll(Bundle.java:292)
	at com.android.bluetooth.avrcp.Util.descriptionToBundle(Util.java:84)
	at com.android.bluetooth.avrcp.Util.toMetadata(Util.java:141)
	at com.android.bluetooth.avrcp.Util.toMetadataList(Util.java:213)
	at com.android.bluetooth.avrcp.MediaPlayerWrapper.<init>(MediaPlayerWrapper.java:92)
	at com.android.bluetooth.avrcp.MediaPlayerWrapperFactory.wrap(MediaPlayerWrapperFactory.java:42)
	at com.android.bluetooth.avrcp.MediaPlayerList.addMediaPlayer(MediaPlayerList.java:482)
	at com.android.bluetooth.avrcp.MediaPlayerList.addMediaPlayer(MediaPlayerList.java:502)
	at com.android.bluetooth.avrcp.MediaPlayerList$1.onActiveSessionsChanged(MediaPlayerList.java:653)
	at android.media.session.MediaSessionManager$SessionsChangedWrapper$1$1.run(MediaSessionManager.java:1146)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7945)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by brahmkshatriya** [comment]
device specification please

**Comment by dxuser1919** [comment]
OS: Android 11
Model: TablePC 
CPU: Unisoc T310

**Comment by brahmkshatriya** [comment]
@dxuser1919 give me an exact method to reproduce it

**Comment by dxuser1919** [comment]
1. Open bluetooth
2. Open Echo
3. Play a audio
4. Bluetooth has stopped

**Comment by brahmkshatriya** [comment]
should be fixed now
