### ISSUE TITLE
when downloading music the app crashes

### ISSUE THREAD

**Issue by siggi1984** [brahmkshatriya/echo#33]
### Summary

as soon as I tap on download the app crashes

### Reproduction Steps

```
java.lang.IllegalArgumentException: Failed requirement.
	at dev.brahmkshatriya.echo.download.Downloader$enqueueDownload$2.invokeSuspend(Downloader.kt:91)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3a988e6, Dispatchers.Main.immediate]

```

### Expected Result

X

### Actual Result

X

### Device Information

Echo Version 1.0.0-f4f8b79, Xiaomi Redmi Note 13, Android 14

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Downloads are currently WIP

**Comment by itsmechinmoy** [comment]
Fixed
