### ISSUE TITLE
Unable to create service dev.brahmkshatriya.echo.PlayerService

### ISSUE THREAD

**Issue by Brajesh3** [brahmkshatriya/echo#43]
### Summary

first thing i see after restarting my device is this error

### Reproduction Steps

1. restart/reboot your device
2. you will see the error

### Expected Result

- not to have this error

### Actual Result

i see this error every single time

### Device Information

Echo version: 1.0.0-b8079d1
Brand: samsung m11
arch: armv7
android version 12

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

```java
java.lang.RuntimeException: Unable to create service dev.brahmkshatriya.echo.PlayerService: java.lang.IllegalArgumentException: Volume external_primary not found
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5035)
	at android.app.ActivityThread.access$1800(ActivityThread.java:315)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.IllegalArgumentException: Volume external_primary not found
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1226)
	at android.content.ContentResolver.query(ContentResolver.java:1158)
	at android.content.ContentResolver.query(ContentResolver.java:1114)
	at dev.brahmkshatriya.echo.offline.MediaStoreUtils.playlistContent(MediaStoreUtils.kt:218)
	at dev.brahmkshatriya.echo.offline.MediaStoreUtils.getAllSongs(MediaStoreUtils.kt:477)
	at dev.brahmkshatriya.echo.offline.OfflineExtension.<init>(OfflineExtension.kt:114)
	at dev.brahmkshatriya.echo.di.ExtensionModule.provideOfflineExtension(ExtensionModule.kt:31)
	at dev.brahmkshatriya.echo.di.ExtensionModule_ProvideOfflineExtensionFactory.provideOfflineExtension(ExtensionModule_ProvideOfflineExtensionFactory.java:53)
	at dev.brahmkshatriya.echo.DaggerEchoApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerEchoApplication_HiltComponents_SingletonC.java:907)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at dev.brahmkshatriya.echo.DaggerEchoApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerEchoApplication_HiltComponents_SingletonC.java:913)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at dev.brahmkshatriya.echo.DaggerEchoApplication_HiltComponents_SingletonC$ServiceCImpl.injectPlayerService2(DaggerEchoApplication_HiltComponents_SingletonC.java:750)
	at dev.brahmkshatriya.echo.DaggerEchoApplication_HiltComponents_SingletonC$ServiceCImpl.injectPlayerService(DaggerEchoApplication_HiltComponents_SingletonC.java:745)
	at dev.brahmkshatriya.echo.Hilt_PlayerService.inject(Hilt_PlayerService.java:53)
	at dev.brahmkshatriya.echo.Hilt_PlayerService.onCreate(Hilt_PlayerService.java:30)
	at dev.brahmkshatriya.echo.PlayerService.onCreate(PlayerService.kt:112)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5022)
	... 9 more

```

**Comment by brahmkshatriya** [comment]
Should be fixed
